[project]
name = "dimpl"
version = "0.1.0"
requires-python = ">=3.12"
authors = [{name = "Aly Kapasi"}]

dependencies = [
    "fastapi>=0.118.0",
    "uvicorn[standard]>=0.37.0",
    "mlflow>=3.4.0",
    "flytekit>=1.16.5",
    "boto3>=1.40.18",
    "psycopg2-binary>=2.9.10",
    "pydantic>=2.11.9",
    "httpx>=0.28.1",
]

[project.scripts]
start-api = "uvicorn app.main:app --host 0.0.0.0 --port 8000"
